=== ajaxx/nesper-dev/NEsper/etc/regression/mediaOrderSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="MediaOrder">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="OrderId" type="xs:string"/>
        <xs:element ref="Items" maxOccurs="1" />
        <xs:element ref="Books" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Items">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Item" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Books">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Book" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Item">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ItemId" type="xs:string"/>
        <xs:element name="ProductId" type="xs:string"/>
        <xs:element name="Amount" type="xs:int"/>
        <xs:element name="Price" type="xs:double"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Book">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="BookId" type="xs:string"/>
        <xs:element name="Author" type="xs:string"/>
        <xs:element ref="Review" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Review">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ReviewId" type="xs:string"/>
        <xs:element name="Comment" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ajaxx/nesper-dev/NEsper/etc/regression/mediaOrderTwo.xml
<?xml version="1.0" encoding="UTF-8"?>
<MediaOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mediaOrderSchema.xsd">
  <OrderId>PO200901</OrderId>
  <Items>
    <Item>
      <ItemId>200001</ItemId>
      <ProductId>B006</ProductId>
      <Amount>7</Amount>
      <Price>7.45</Price>
    </Item>
    <Item>
      <ItemId>200002</ItemId>
      <ProductId>B005</ProductId>
      <Amount>1</Amount>
      <Price>67.99</Price>
    </Item>
    <Item>
      <ItemId>200003</ItemId>
      <ProductId>B007</ProductId>
      <Amount>0</Amount>
      <Price>0</Price>
    </Item>
    <Item>
      <ItemId>200004</ItemId>
      <ProductId>B005</ProductId>
      <Amount>2</Amount>
      <Price>63.99</Price>
    </Item>
  </Items>
  <Books>
    <Book>
      <BookId>B005</BookId>
      <Author>Heinlein</Author>
      <Review>
        <Reviewid>1</Reviewid>
        <Comment>best Book ever</Comment>
      </Review>
      <Review>
        <Reviewid>2</Reviewid>
        <Comment>would recommend</Comment>
      </Review>
    </Book>
    <Book>
      <BookId>B006</BookId>
      <Author>Isaac Asimov</Author>
    </Book>
    <Book>
      <BookId>B008</BookId>
      <Author>Ian M Banks</Author>
    </Book>
  </Books>
</MediaOrder>

=== ajaxx/nesper-dev/NEsper/etc/regression/mediaOrderOne.xml
<?xml version="1.0" encoding="UTF-8"?>
<MediaOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mediaOrderSchema.xsd">
  <OrderId>PO200901</OrderId>
  <Items>
    <Item>
      <ItemId>100001</ItemId>
      <ProductId>B001</ProductId>
      <Amount>10</Amount>
      <Price>11.95</Price>
    </Item>
  </Items>
  <Books>
    <Book>
      <BookId>B001</BookId>
      <Author>Orson Scott Card</Author>
      <Review>
        <ReviewId>1</ReviewId>
        <Comment>best Book ever</Comment>
      </Review>
    </Book>
    <Book>
      <BookId>B002</BookId>
      <Author>Isaac Asimov</Author>
    </Book>
  </Books>
</MediaOrder>
